In [1]:
# Built-in dependencies
import sys
from typing import Optional

# External dependencies
import numpy as np
import pandas as pd

In [6]:
# Local dependencies
sys.path.append(r"C:\Users\marcu\Documents\Quant\Programming\real_estate")
from real_estate.models import ExpenseModel
from real_estate.models.random_variables import BoundedNormalRandomVariable, RandomVariable

In [7]:
# Define None expense for testing
HOA_EXPENSE: Optional[float] = None

# Define constant expense for testing
INSURACE_EXPENSE: float = 150.0

# Define random expense for testing
UTILITY_EXPENSE_MU: float = 100.0
UTILITY_EXPENSE_SIGMA: float = 20.0
UTILITY_EXPENSE_LOWER_BOUND: float = 50.0
UTILITY_EXPENSE_UPPER_BOUND: float = 200.0
UTILITY_EXPENSE: RandomVariable = BoundedNormalRandomVariable(mu=UTILITY_EXPENSE_MU, sigma=UTILITY_EXPENSE_SIGMA, lower_bound=UTILITY_EXPENSE_LOWER_BOUND, upper_bound=UTILITY_EXPENSE_UPPER_BOUND)

In [8]:
expense_model = ExpenseModel(hoa_expense=HOA_EXPENSE, insurance_expense=INSURACE_EXPENSE, utility_expense=UTILITY_EXPENSE)

In [9]:
expense_model(), expense_model(shape=(2, 10))

(192.42861477483046,
 array([[264.82064938, 223.68088897, 264.14776006, 266.22632088,
         205.04071228, 285.84132946, 243.65933814, 230.40539709,
         276.32176996, 240.73628532],
        [230.86322899, 253.04429915, 264.5521373 , 249.01643812,
         253.36180317, 267.71801519, 244.86583092, 292.00570494,
         255.82944783, 239.45297871]]))

In [10]:
hoa_expense_model = ExpenseModel(hoa_expense=HOA_EXPENSE)
hoa_expense_model(), hoa_expense_model(shape=(2, 10)) 

(0.0,
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]))

In [11]:
insurance_expense_model = ExpenseModel(insurance_expense=INSURACE_EXPENSE)
insurance_expense_model(), insurance_expense_model(shape=(2, 10)) 

(150.0,
 array([[150., 150., 150., 150., 150., 150., 150., 150., 150., 150.],
        [150., 150., 150., 150., 150., 150., 150., 150., 150., 150.]]))

In [20]:
utility_expense_model = ExpenseModel(utility_expense=UTILITY_EXPENSE)
utility_expense_model(), utility_expense_model(shape=(2, 10))

(46.69340803794749,
 array([[ 88.32780233, 121.22664315,  94.44652828, 122.07241332,
          80.22530624, 119.53648982, 108.32006645,  86.39007683,
          90.93295588, 114.85773238],
        [ 76.55434328,  69.6669952 , 151.51493547,  85.42155441,
         119.80288826, 118.20418971, 100.08420768,  97.53498001,
          84.35762134, 104.17988713]]))