In [1]:
# Built-in dependencies
import sys
from typing import Optional

# External dependencies
import numpy as np
import pandas as pd

In [2]:
# Local dependencies
sys.path.append(r"C:\Users\marcu\Documents\Quant\Programming\real_estate")
from real_estate.models import ExpenseModel
from real_estate.models.random_variables import BoundedNormalRandomVariable, RandomVariable

In [3]:
# Define None expense for testing
HOA_EXPENSE: Optional[float] = None

# Define constant expense for testing
INSURACE_EXPENSE: float = 150.0

# Define random expense for testing
UTILITY_EXPENSE_MU: float = 100.0
UTILITY_EXPENSE_SIGMA: float = 20.0
UTILITY_EXPENSE_LOWER_BOUND: float = 50.0
UTILITY_EXPENSE_UPPER_BOUND: float = 200.0
UTILITY_EXPENSE: RandomVariable = BoundedNormalRandomVariable(mu=UTILITY_EXPENSE_MU, sigma=UTILITY_EXPENSE_SIGMA, lower_bound=UTILITY_EXPENSE_LOWER_BOUND, upper_bound=UTILITY_EXPENSE_UPPER_BOUND)

In [4]:
expense_model = ExpenseModel(hoa_expense=HOA_EXPENSE, insurance_expense=INSURACE_EXPENSE, utility_expense=UTILITY_EXPENSE)

In [23]:
expense_model(), expense_model(shape=(2, 10))

(197.53121516254538,
 array([[277.24251106, 252.61198981, 271.323535  , 253.83238396,
         211.41782543, 259.31570902, 236.67502232, 227.61949596,
         244.50442299, 249.34674024],
        [236.80114899, 264.0175464 , 226.05640857, 241.17110008,
         261.3973012 , 251.47830559, 222.21372539, 232.64512052,
         233.79494626, 228.07909317]]))

In [24]:
hoa_expense_model = ExpenseModel(hoa_expense=HOA_EXPENSE)
hoa_expense_model(), hoa_expense_model(shape=(2, 10)) 

(0.0,
 array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]))

In [27]:
insurance_expense_model = ExpenseModel(insurance_expense=INSURACE_EXPENSE)
insurance_expense_model(), insurance_expense_model(shape=(2, 10)) 

(150.0,
 array([[150., 150., 150., 150., 150., 150., 150., 150., 150., 150.],
        [150., 150., 150., 150., 150., 150., 150., 150., 150., 150.]]))

In [31]:
utility_expense_model = ExpenseModel(utility_expense=UTILITY_EXPENSE)
utility_expense_model(), utility_expense_model(shape=(2, 10)) 

(49.2495231180509,
 array([[ 89.33967448,  87.65238142,  65.92014773,  90.31294423,
          85.81230074, 109.79206884, 126.55147619,  78.43456106,
          99.08572621,  80.83293253],
        [123.48226101,  79.20051777,  95.40881801, 119.29964939,
         128.80883063, 104.04873287,  83.92938058, 102.87463247,
         128.80646723,  93.18968099]]))